
repos:
  # Black - форматирование кода
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--config=pyproject.toml]

  # Flake8 - линтинг кода
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        args: [--config=.flake8]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace  # удаляет пробелы в конце строк
      - id: end-of-file-fixer    # добавляет пустую строку в конце файла
      - id: check-yaml           # проверяет синтаксис YAML
      - id: check-json           # проверяет синтаксис JSON
      - id: check-added-large-files  # проверяет большие файлы
        args: ['--maxkb=500']
      - id: check-merge-conflict      # проверяет конфликты слияния
      - id: debug-statements          # проверяет отладочные операторы
      - id: detect-private-key        # проверяет приватные ключи
